from flask_restx import reqparse

customer_parser = reqparse.RequestParser() 
customer_parser.add_argument("email", type=str, location='form')
customer_parser.add_argument("name", type=str, location='form')
customer_parser.add_argument("password", type=str, location='form')
customer_parser.add_argument("building_number", type=str, location='form')
customer_parser.add_argument("street", type=str, location='form')
customer_parser.add_argument("city", type=str, location='form')
customer_parser.add_argument("state", type=str, location='form')
customer_parser.add_argument("phone_number", type=str, location='form')
customer_parser.add_argument("passport_number", type=str, location='form')
customer_parser.add_argument("passport_expiration", type=str, location='form')
customer_parser.add_argument("passport_country", type=str, location='form')
customer_parser.add_argument("date_of_birth", type=str, location='form')

airline_staff_parser = reqparse.RequestParser() 
airline_staff_parser.add_argument("username", type=str, location='form')
airline_staff_parser.add_argument("password", type=str, location='form')
airline_staff_parser.add_argument("first_name", type=str, location='form')
airline_staff_parser.add_argument("last_name", type=str, location='form')
airline_staff_parser.add_argument("date_of_birth", type=str, location='form')
airline_staff_parser.add_argument("airline", type=str, location='form')
airline_staff_parser.add_argument("phone_number", type=str, location='form')

airport_parser = reqparse.RequestParser() 
airport_parser.add_argument("airport_code", type=str, location='form')
airport_parser.add_argument("name", type=str, location='form')
airport_parser.add_argument("city", type=str, location='form')
airport_parser.add_argument("country", type=str, location='form')
airport_parser.add_argument("type", type=str, location='form')

purchase_parser = reqparse.RequestParser() 
purchase_parser.add_argument("customer_email", type=str, location='form')
purchase_parser.add_argument("card_type", type=str, location='form')
purchase_parser.add_argument("card_number", type=str, location='form')
purchase_parser.add_argument("name_on_card", type=str, location='form')
purchase_parser.add_argument("card_expiration", type=str, location='form')
purchase_parser.add_argument("travel_class", type=str, location='form')
purchase_parser.add_argument("airline_name", type=str, location='form')
purchase_parser.add_argument("flight_number", type=str, location='form')
purchase_parser.add_argument("departure_date_time", type=str, location='form')

flight_parser = reqparse.RequestParser() 
flight_parser.add_argument("flight_number", type=str, location='form')
flight_parser.add_argument("airplane_id", type=str, location='form')
flight_parser.add_argument("departure_date_time", type=str, location='form')
flight_parser.add_argument("departure_airport_code", type=str, location='form')
flight_parser.add_argument("arrival_date_time", type=str, location='form')
flight_parser.add_argument("arrival_airport_code", type=str, location='form')
flight_parser.add_argument("base_price", type=float, location='form')
flight_parser.add_argument("status", type=str, location='form')
flight_parser.add_argument("airline_name", type=str, location='form')

airplane_parser = reqparse.RequestParser() 
airplane_parser.add_argument("ID", type=str, location='form')
airplane_parser.add_argument("airline_name", type=str, location='form')
airplane_parser.add_argument("number_of_seats", type=int, location='form')
airplane_parser.add_argument("manufacturer", type=str, location='form')
airplane_parser.add_argument("age", type=int, location='form')

rate_comment_parser = reqparse.RequestParser()
rate_comment_parser.add_argument("ticket_id", type=str, location='form')
rate_comment_parser.add_argument("rating", type=int, location='form')
rate_comment_parser.add_argument("comment", type=str, location='form')